Repository jtrenaud1s/GLang, pull requests merged in 2020-11, with the labels that each got.

#33 Created base interpreter and an example program.
  pom.xml
  src/main/java/edu/semo/jatsz/glang/Lexer.java
  src/main/java/edu/semo/jatsz/glang/ParseTree.java
  src/main/java/edu/semo/jatsz/glang/Parser.java
  src/main/java/edu/semo/jatsz/glang/Tokens.java
  src/main/java/edu/semo/jatsz/glang/model/SymbolStorage.java
  src/main/java/edu/semo/jatsz/glang/model/SymbolTable.java
  src/main/java/edu/semo/jatsz/glang/parsenode/BinaryOperationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/GroupNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ParseNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ReferenceNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/Symbol.java
  src/main/java/edu/semo/jatsz/glang/parsenode/Type.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/AssignmentNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/DeclarationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StatementListNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StatementNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StdInNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StdOutNode.java
  src/main/resources/GLang.jacc
  src/main/resources/jacc.bat
  src/main/resources/jacc.jar
  test.g
Labels: enhancement

#36 added my name
  README.md
Labels: enhancement, good first issue

#39 Zach philipp
  README.md
Labels: good first issue

#41 Added DOUBLE type support
  src/main/java/edu/semo/jatsz/glang/Lexer.java
  src/main/java/edu/semo/jatsz/glang/Parser.java
  src/main/java/edu/semo/jatsz/glang/Tokens.java
  src/main/java/edu/semo/jatsz/glang/parsenode/BinaryOperationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/Symbol.java
  src/main/java/edu/semo/jatsz/glang/parsenode/Type.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/AssignmentNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StdInNode.java
  src/main/resources/GLang.jacc
  test.g
Labels: enhancement

#42 added multiplication and division binary operators
  src/main/java/edu/semo/jatsz/glang/Lexer.java
  src/main/java/edu/semo/jatsz/glang/Parser.java
  src/main/java/edu/semo/jatsz/glang/Tokens.java
  src/main/java/edu/semo/jatsz/glang/parsenode/BinaryOperationNode.java
  src/main/resources/GLang.jacc
  test.g
Labels: enhancement

#43 Adding a power
  src/main/java/edu/semo/jatsz/glang/Lexer.java
  src/main/java/edu/semo/jatsz/glang/Parser.java
  src/main/java/edu/semo/jatsz/glang/Tokens.java
  src/main/java/edu/semo/jatsz/glang/parsenode/BinaryOperationNode.java
  src/main/resources/GLang.jacc
  test.g
Labels: enhancement

#44 added a while loop
  src/main/java/edu/semo/jatsz/glang/Lexer.java
  src/main/java/edu/semo/jatsz/glang/Parser.java
  src/main/java/edu/semo/jatsz/glang/Tokens.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/WhileStatementNode.java
  src/main/resources/GLang.jacc
  test.g
Labels: enhancement

#49 Added scope environments to StatementLists and reworked EVERY NODE to…
  src/main/java/edu/semo/jatsz/glang/ParseTree.java
  src/main/java/edu/semo/jatsz/glang/Parser.java
  src/main/java/edu/semo/jatsz/glang/Tokens.java
  src/main/java/edu/semo/jatsz/glang/model/SymbolStorage.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ArrayReferenceNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/BinaryOperationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/GroupNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ParseNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ReferenceNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/Symbol.java
  src/main/java/edu/semo/jatsz/glang/parsenode/UnaryOperationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/ArrayDeclarationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/AssignmentNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/DeclarationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/ForStatementNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StatementListNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StdInNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StdOutNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/WhileStatementNode.java
  src/main/resources/GLang.jacc
  test.g
Labels: enhancement

#50 Added inline variable definition support;
  src/main/java/edu/semo/jatsz/glang/Parser.java
  src/main/java/edu/semo/jatsz/glang/Tokens.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/AssignmentNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/DeclarationNode.java
  src/main/resources/GLang.jacc
  test.g
Labels: enhancement

#52 Added functions, instance specific functions!!!!! if, else, else if s…
  pom.xml
  src/main/java/edu/semo/jatsz/glang/Lexer.java
  src/main/java/edu/semo/jatsz/glang/ParseTree.java
  src/main/java/edu/semo/jatsz/glang/Parser.java
  src/main/java/edu/semo/jatsz/glang/Tokens.java
  src/main/java/edu/semo/jatsz/glang/model/SymbolStorage.java
  src/main/java/edu/semo/jatsz/glang/model/SymbolTable.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ArrayReferenceNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ArraySymbol.java
  src/main/java/edu/semo/jatsz/glang/parsenode/BinaryOperationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/GroupNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ReferenceNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/Symbol.java
  src/main/java/edu/semo/jatsz/glang/parsenode/UnaryOperationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/classnode/ClassDeclarationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/classnode/ClassDefinitionNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/classnode/FieldReferenceNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/function/FunctionCallStatement.java
  src/main/java/edu/semo/jatsz/glang/parsenode/function/FunctionDefinitionNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/function/FunctionSymbol.java
  src/main/java/edu/semo/jatsz/glang/parsenode/function/ReturnStatementNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/ArrayDeclarationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/AssignmentNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/DeclarationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/ForStatementNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/IfStatementNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StatementListNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StdInNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StdOutNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/WhileStatementNode.java
  src/main/resources/GLang.jacc
  src/main/resources/test.g
  src/main/resources/test.tokens
  test.g
Labels: enhancement

#53 Fixes
  dog.g
  src/main/java/edu/semo/jatsz/glang/ParseTree.java
  src/main/java/edu/semo/jatsz/glang/Parser.java
  src/main/java/edu/semo/jatsz/glang/Tokens.java
  src/main/java/edu/semo/jatsz/glang/model/SymbolStorage.java
  src/main/java/edu/semo/jatsz/glang/model/SymbolTable.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ArrayReferenceNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ArraySymbol.java
  src/main/java/edu/semo/jatsz/glang/parsenode/BinaryOperationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/GroupNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ParseNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/ReferenceNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/Symbol.java
  src/main/java/edu/semo/jatsz/glang/parsenode/UnaryOperationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/classnode/ClassDeclarationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/classnode/ClassDefinitionNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/classnode/FieldReferenceNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/function/FunctionCallStatement.java
  src/main/java/edu/semo/jatsz/glang/parsenode/function/FunctionDefinitionNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/function/ReturnStatementNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/ArrayDeclarationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/AssignmentNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/DeclarationNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/ForStatementNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/IfStatementNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StatementListNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StdInNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/StdOutNode.java
  src/main/java/edu/semo/jatsz/glang/parsenode/statement/WhileStatementNode.java
  src/main/resources/GLang.jacc
  src/main/resources/test.tokens
  test.g
Labels: enhancement
